#' @include utilities.R dist.R
NULL
#' Assessing Clustering Tendency
#' 
#' @description Before applying clustering methods, assess whether the data show
#'   non-random structure, a process known as \strong{assessing clustering
#'   tendency}. \code{get_clust_tendency()} uses the Hopkins statistic and,
#'   optionally, an ordered dissimilarity image (ODI). Rows containing missing
#'   values are omitted, and the remaining matrix must be numeric and finite.
#'   The observed rows are sampled without replacement; artificial points are
#'   sampled uniformly within the observed bounding box. Zero-range columns are
#'   ignored for the Hopkins calculation when at least one column varies; an
#'   all-constant data set remains undefined. In the ODI, objects
#'   grouped by hierarchical clustering are displayed in consecutive order.
#'   For more details and
#'   interpretation, see 
#'   \href{https://www.datanovia.com/en/lessons/assessing-clustering-tendency/}{STHDA
#'    website: Assessing clustering tendency}.
#' @param data a numeric data frame or matrix. Columns are variables and rows
#'   are samples. Computations are performed on complete rows. To calculate the
#'   Hopkins statistic for variables, transpose the data first.
#' @param n a positive integer specifying the number of points selected from
#'   sample space and from the observed data. Must be smaller than the number
#'   of complete observations.
#' @param graph logical value; if TRUE the ordered dissimilarity image (ODI) is 
#'   shown.
#' @param gradient a list containing three elements specifying the colors for 
#'   low, mid and high values in the ordered dissimilarity image. The element 
#'   "mid" can take the value of NULL.
#' @param seed an integer seed for reproducibility, or NULL to use the current
#'   RNG stream. When non-NULL, the function restores the caller RNG state on
#'   exit.
#' @details
#' 
#' \strong{Hopkins statistic}: Values near 1 support a clustered tendency,
#' values near 0.5 are consistent with complete spatial randomness, and values
#' near 0 indicate regular spacing. The statistic uses the formula from Cross
#' and Jain (1982), with exponent \eqn{d = D}, where \eqn{D} is the number of
#' varying columns. Redundant constant columns therefore do not change the
#' statistic. A Beta(\eqn{n}, \eqn{n}) comparison is an approximation under ideal
#' complete-spatial-randomness assumptions, not an unconditional finite-sample
#' distribution for every data set.
#'
#' \strong{Note on interpretation}: This function returns the Hopkins statistic H
#' where values close to 1 indicate clusterable data. Some other packages (e.g.,
#' \code{performance::check_clusterstructure}) return 1-H, where values close to
#' 0 indicate clusterability. Always check the documentation of the specific
#' implementation you are using.
#'
#' \strong{Breaking change}: factoextra uses the corrected Hopkins statistic
#' formula (Wright 2022). Results differ from legacy factoextra and a one-time
#' warning is emitted. Set \code{options(factoextra.warn_hopkins = FALSE)} to
#' silence the warning.
#'
#' For large datasets, nearest-neighbor distances are computed with a low-memory
#' fallback when the full pairwise matrix would exceed
#' \code{getOption("factoextra.hopkins.max_matrix_cells", 2e7)} cells.
#' Only the sampled row's own occurrence is excluded from its nearest-neighbor
#' search; a duplicated row therefore remains a valid zero-distance neighbor.
#' 
#' \strong{VAT (Visual Assessment of Cluster Tendency)}: The VAT displays
#' clustering tendency by showing square-shaped
#' dark (or colored) blocks along the diagonal in a VAT image.
#'  
#' @return A list containing:
#'   \item{hopkins_stat}{The Hopkins statistic.}
#'   \item{plot}{The ordered dissimilarity image generated by
#'   \code{\link{fviz_dist}}(), or \code{NULL} when \code{graph = FALSE}.}
#' @seealso \code{\link{fviz_dist}}
#' @author Alboukadel Kassambara \email{alboukadel.kassambara@@gmail.com}
#' @examples 
#' data(iris)
#' 
#' # Silence the one-time compatibility warning in examples
#' old_hopkins_warn <- getOption("factoextra.warn_hopkins")
#' options(factoextra.warn_hopkins = FALSE)
#' 
#' # Clustering tendency
#' gradient_col = list(low = "steelblue", high = "white")
#' get_clust_tendency(iris[,-5], n = 50, gradient = gradient_col)
#'    
#' # Random uniformly distributed dataset
#' # (without any inherent clusters)
#' set.seed(123)
#' random_df <- apply(iris[, -5], 2, 
#'                    function(x){runif(length(x), min(x), max(x))}
#'                    )
#' get_clust_tendency(random_df, n = 50, gradient = gradient_col)
#' options(factoextra.warn_hopkins = old_hopkins_warn)
#' 
#' @export
get_clust_tendency <- function(data, n, graph = TRUE,
                               gradient = list(low = "red", mid = "white", high = "blue"),
                               seed = NULL) 
{
  if (is.data.frame(data)) 
    data <- as.matrix(data)
  if (!(is.matrix(data))) 
    stop("data must be data.frame or matrix")
  if (!is.numeric(data))
    stop("data must contain numeric values only")
  if (!is.numeric(n) || length(n) != 1L || is.na(n) || !is.finite(n) ||
      n < 1 || n %% 1 != 0)
    stop("n must be a positive integer")

  data <- na.omit(data)
  if (nrow(data) < 2)
    stop("data must contain at least two complete rows")
  if(any(!is.finite(data)))
    stop("data must contain finite values only")
  if (n >= nrow(data))
    stop("n must be smaller than the number of complete samples")
  rownames(data) <- paste0("r", seq_len(nrow(data)))

  if (!is.null(seed)) {
    has_seed <- exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
    if (has_seed) old_seed <- get(".Random.seed", envir = .GlobalEnv)
    on.exit({
      if (!has_seed && exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) {
        rm(".Random.seed", envir = .GlobalEnv)
      } else if (has_seed) {
        assign(".Random.seed", old_seed, envir = .GlobalEnv)
      }
    }, add = TRUE)
    set.seed(seed)
  }

  if (isTRUE(getOption("factoextra.warn_hopkins", TRUE)) &&
      !isTRUE(.factoextra_state$hopkins_warned)) {
    warning(
      "Hopkins statistic uses the corrected formula (Wright 2022); results ",
      "differ from legacy factoextra. Set options(factoextra.warn_hopkins = FALSE) ",
      "to silence this warning.",
      call. = FALSE
    )
    .factoextra_state$hopkins_warned <- TRUE
  }
  plot <- NULL

  # Hopkins is invariant to a common translation and positive scale. Put the
  # coordinates in a safe numeric range before squaring distances so finite data
  # expressed in very small or very large units do not underflow or overflow.
  hopkins_data <- matrix(
    0, nrow = nrow(data), ncol = ncol(data), dimnames = dimnames(data)
  )
  varying <- vapply(
    seq_len(ncol(data)),
    function(j) min(data[, j]) != max(data[, j]),
    logical(1)
  )
  if(any(varying)){
    active <- which(varying)
    column_scales <- vapply(
      active, function(j) max(abs(data[, j])), numeric(1)
    )
    global_scale <- max(column_scales)
    for(i in seq_along(active)){
      j <- active[i]
      normalized <- data[, j] / column_scales[i]
      hopkins_data[, j] <-
        (normalized - normalized[1]) * (column_scales[i] / global_scale)
    }
    coordinate_span <- max(abs(hopkins_data))
    if(!is.finite(coordinate_span) || coordinate_span <= 0)
      stop("Unable to rescale the data for stable distance computation.")
    hopkins_data <- hopkins_data / coordinate_span
  }
  if(any(varying) && !all(varying))
    hopkins_data <- hopkins_data[, varying, drop = FALSE]

  if(graph){
    plot_dist <- stats::dist(data)
    raw_distances <- unclass(plot_dist)
    # Preserve ordinary graph distances, but use the stable similarity
    # transform when raw squaring overflows or collapses every distance to zero.
    if(any(!is.finite(raw_distances)) ||
       (any(varying) && !any(raw_distances > 0)))
      plot_dist <- stats::dist(hopkins_data)
    plot <- fviz_dist(plot_dist, order = TRUE,
                      show_labels = FALSE, gradient = gradient)
  }
  
  # Hopkins statistic
  # Sample synthetic points uniformly within the observed ranges.
  mins <- vapply(
    seq_len(ncol(hopkins_data)),
    function(j) min(hopkins_data[, j]),
    numeric(1)
  )
  maxs <- vapply(
    seq_len(ncol(hopkins_data)),
    function(j) max(hopkins_data[, j]),
    numeric(1)
  )
  p <- matrix(NA_real_, nrow = n, ncol = ncol(hopkins_data))
  for(j in seq_len(ncol(hopkins_data)))
    p[, j] <- runif(n, min = mins[j], max = maxs[j])

  # Use sample() for uniform row selection (fixes biased sampling from PR #133).
  k <- .sample_hopkins_rows(nrow(hopkins_data), n)
  q <- hopkins_data[k, , drop = FALSE]

  max_matrix_cells <- getOption("factoextra.hopkins.max_matrix_cells", 2e7)
  if(!is.numeric(max_matrix_cells) || length(max_matrix_cells) != 1L ||
     is.na(max_matrix_cells) || max_matrix_cells <= 0){
    max_matrix_cells <- 2e7
  }

  use_vectorized <-
    (nrow(p) * nrow(hopkins_data) <= max_matrix_cells) &&
    (nrow(q) * nrow(hopkins_data) <= max_matrix_cells)

  euclid_sq <- function(a, b){
    a_sq <- rowSums(a^2)
    b_sq <- rowSums(b^2)
    # Squared Euclidean distances between all rows of a and b.
    pmax(outer(a_sq, b_sq, "+") - 2 * tcrossprod(a, b), 0)
  }

  min_sq_dist <- function(a, b, exclude_index = NULL){
    if(use_vectorized){
      d2 <- euclid_sq(a, b)
      if(!is.null(exclude_index))
        d2[cbind(seq_len(nrow(a)), exclude_index)] <- Inf
      mins <- apply(d2, 1, min)
      if(any(!is.finite(mins)))
        stop("Unable to compute finite nearest-neighbour distances.")
      return(mins)
    }

    # Chunked fallback keeps memory bounded while preserving vectorized math.
    chunk_size <- floor(max_matrix_cells / nrow(b))
    if(!is.finite(chunk_size) || chunk_size < 1) chunk_size <- 1
    chunk_size <- as.integer(chunk_size)
    mins <- numeric(nrow(a))
    starts <- seq.int(1L, nrow(a), by = chunk_size)
    for(start in starts){
      end <- min(start + chunk_size - 1L, nrow(a))
      idx <- start:end
      d2 <- euclid_sq(a[idx, , drop = FALSE], b)
      if(!is.null(exclude_index))
        d2[cbind(seq_len(nrow(d2)), exclude_index[idx])] <- Inf
      block_mins <- apply(d2, 1, min)
      if(any(!is.finite(block_mins)))
        stop("Unable to compute finite nearest-neighbour distances.")
      mins[idx] <- block_mins
    }
    mins
  }

  minp <- sqrt(min_sq_dist(p, hopkins_data))
  minq <- sqrt(min_sq_dist(q, hopkins_data, exclude_index = k))
  
  # Hopkins statistic formula fix: use exponent d=D (dimensionality) as per

  # Cross & Jain (1982) "Measurement of Clustering Tendency" and
  # Wright (2022) "Will the Real Hopkins Statistic Please Stand Up?" R Journal.
  # Previous implementation incorrectly used d=1; the corrected formula uses the
  # effective dimensionality after zero-range columns have been removed.
  d <- ncol(hopkins_data)
  distance_scale <- max(c(minp, minq))
  if(!is.finite(distance_scale) || distance_scale <= 0)
    stop("Hopkins statistic is undefined because all nearest-neighbour distances are zero.")
  w <- sum((minp / distance_scale)^d)
  u <- sum((minq / distance_scale)^d)
  denominator <- w + u
  if(!is.finite(denominator) || denominator <= 0)
    stop("Hopkins statistic is undefined because its denominator is zero.")
  list(hopkins_stat = w / denominator, plot = plot)
}

.sample_hopkins_rows <- function(n_rows, n){
  sample.int(n_rows, n, replace = FALSE)
}
