name: R-CMD-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            r: release
            extra_packages: any::rcmdcheck
          - os: ubuntu-latest
            r: devel
            extra_packages: any::rcmdcheck
          - os: ubuntu-latest
            r: oldrel-1
            extra_packages: any::rcmdcheck, any::ggrepel@0.9.5
          - os: macos-latest
            r: release
            extra_packages: any::rcmdcheck
          - os: windows-latest
            r: release
            extra_packages: any::rcmdcheck
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check
          extra-packages: ${{ matrix.extra_packages }}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
